services:

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - global

  app:
    image: webdevops/php-apache:7.4
    restart: always
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - APPLICATION_USER=www-data
      - APPLICATION_GROUP=www-data
    networks:
      - global
    depends_on:
      - mysql

  admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${DB_HOST}
    networks:
      - global
    depends_on:
      - mysql

networks:
  global:
    external: true
