SET NAMES 'utf8' COLLATE 'utf8_bin';

-- стиль: гопник
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай и иди двигайся, хватит киснуть', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сегодня жара, аж асфальт плавится', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, братан, живи по понятиям', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('слушай, ты мне нравишься, без базара', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты с какого района', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че такая красивая, аж в глазах рябит', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я с тобой не пойду, без обид', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне тут рамсы путаешь', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, я погорячился', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('еще раз подойдешь — пожалеешь', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ой да ладно, ты че как маленький', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, братан, все будет по-нашему', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь боль, а ты че хотел', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты сегодня красава, реально', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че тупой совсем, головой думай', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги донести, я же не чужой', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, сам разбирайся, мне некогда', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погнали за гаражи, там посидим', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, у меня дела', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, по рукам', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне лапшу на уши вешаешь', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, я был не прав, признаю', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('это ты во всем виноват', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, я так не думаю', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну ладно, уговорил', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че, я тебе не верю', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че серьезно, вот это поворот', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, ты че наделал', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас стрелу забьем, все решим', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, наконец-то по-нашему', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че-то грустно, братан, тоска', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, ты меня достал', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, че делать будем', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал как собака, сил нет', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать охота, аж живот сводит', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, глаза слипаются', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, одни долги', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник козел, задолбал', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, красава', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она меня бросила, вот тема', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, вот и верь людям', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители достали, че делать', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, бесит', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в танки погоняем', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, нормальную', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку пойдешь', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку погнали', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в чем смысл жизни, братан', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я же пацан', 'гопник');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, бывай, увидимся', 'гопник');

-- стиль: дворовый
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай и иди, хватит лежать', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сегодня дождь, весь двор мокрый', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, сосед, расти большой', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('слушай, ты мне нравишься, честно', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты новенький что ли', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че такая красивая, аж мяч выпал', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я с тобой не пойду, извини', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне тут рамсы путаешь', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, я не хотел', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('еще раз — и по-плохому', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ой да ладно, ты че как маленький', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, все будет норм', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь боль, а ты че хотел', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты сегодня красава, реально', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че тупой, головой думай', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги донести, я же не чужой', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, сам разбирайся, мне некогда', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погнали на площадку, там посидим', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, у меня дела', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, по рукам', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне лапшу вешаешь', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, я был не прав, признаю', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('это ты во всем виноват', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, я так не думаю', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну ладно, уговорил', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че, я тебе не верю', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че серьезно, вот это поворот', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, ты че наделал', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас на лавке все решим', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, наконец-то по-нашему', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че-то грустно, тоска', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, ты меня достал', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, че делать будем', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал как собака, сил нет', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать охота, аж живот сводит', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, глаза слипаются', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, одни долги', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник козел, задолбал', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, красава', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она меня бросила, вот тема', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, вот и верь людям', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители достали, че делать', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, бесит', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в танки погоняем', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, нормальную', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку пойдешь', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку погнали', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в чем смысл жизни', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я же пацан', 'дворовый');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, бывай, увидимся', 'дворовый');

-- стиль: быдло
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, лошара, дел полно', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че за погода, опять сыро', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днем рождения, короче', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты кто вообще', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че такая, пошли гулять', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('отвали, не до тебя', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че, самый умный', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, проехали', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас получишь, понял', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, лох', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не ссы, прорвемся', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('все плохо, ну и че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('молодец, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, че сказать', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, че тебе жалко', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я че рыжий', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли отсюда', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, не пойду', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну ладно, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну извини, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, все', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас разберемся', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я злой', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник дурак', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья кинули', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители достали', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни, че', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь', 'быдло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, пока', 'быдло');

-- стиль: шпана
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, хватит дрыхнуть', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода дрянь, весь день льет', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, брат', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, честно', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты чей будешь', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че такая, пошли погуляем', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, отвали', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас получишь', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, лох', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('все плохо, ну и че', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('молодец', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли отсюда', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, не пойду', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну извини', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты че', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас разберемся', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я злой', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник дурак', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья кинули', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители достали', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь', 'шпана');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, пока', 'шпана');

-- стиль: урка
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, дела ждут', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода шепчет, бери зонт', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, брат, здоровья', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне по душе, слышь', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты чей', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че такая, пошли', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, не по пути', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас ответишь', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, лох', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('все плохо, ну и че', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('молодец', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли отсюда', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, не пойду', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну извини', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты че', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас разберемся', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я злой', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник дурак', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья кинули', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители достали', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь', 'урка');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, пока', 'урка');

-- стиль: эмо
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, жизнь ждет', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('дождь идет, и я плачу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, живи как хочешь', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, но я боюсь', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты меня понимаешь', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, я не могу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не достоин', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че меня не любишь', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, прости меня', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я умру без тебя', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, все равно больно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, я с тобой', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь боль, я знаю', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, правда', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, но я терплю', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, мне плохо', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам разбирайся, я устал', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли, тут темно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я останусь дома', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но я страдаю', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне врешь', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я виноват', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, и мне больно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, я согласен', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, и это больно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, я в шоке', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, мне плохо', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас все рухнет', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, но я все равно грущу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, как всегда', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол и плачу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно и больно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, сил нет', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, но не могу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но не спится', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, и это грустно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник злой, я плачу', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, но не рад', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, я в печали', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, больно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, бесит', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, отвлечемся', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, грустную', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, может отпустит', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, но мне грустно', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в чем смысл, я не знаю', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я устал', 'эмо');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, прощай навсегда', 'эмо');

-- стиль: гот
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, тьма ждет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода мрачная, как я', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, живи в тени', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, тьма свела', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты из наших', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая бледная, красиво', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я один по жизни', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че меня не боишься', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но тьма рядом', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас прокляну', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, смертные', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, тьма поможет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь боль, я знал', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, для смертного', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как свет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, мне нужна жертва', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я во тьме', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на кладбище', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я останусь в склепе', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, кровью подпишем', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че мне врешь, смертный', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я был во тьме', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, тьма накажет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, смертный', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, я согласен', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, я никому не верю', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это тьма', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, тьма удивила', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас ритуал проведем', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, тьма победила', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, как всегда', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, тьма во мне', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, даже смерть скучна', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, хочу в тень', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, но я постюсь', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, в гробу', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, и это мрачно', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник светлый, бесит', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, но тьма ждет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла во тьму', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, как всегда', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают тьму', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, мрак', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, мрачные', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, готичную', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, тьма зовет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, в склепе', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни во тьме', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я жду', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, уходи во тьму', 'гот');

-- стиль: гот (остаток 17)
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, ночь наша', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('туман стелется, красота', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, смертный', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, как тень', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты из склепа', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая бледная, идеал', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я с живыми не общаюсь', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че не боишься тьмы', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но не надейся', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас наведу порчу', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, жалкие смертные', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, тьма не отпустит', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь боль, а смерть подруга', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, почти как тень', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как рассвет', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, мне нужна кровь', 'гот');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я уже мертв внутри', 'гот');

-- стиль: панк
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай и рви этот день', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода дрянь, и это круто', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, анархия', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, панк', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че хотел', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж ирокез дыбом', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, система не по мне', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, панк', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но систему не люблю', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас все разнесу', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, копы сосут', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, панк, прорвемся', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь дрянь, но нам норм', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, бунтарь', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как система', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, панк, не бросай', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я свободен', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на сквот', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, я в отрыве', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без правил', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, система', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я был пьян', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, система', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, я бунтарь', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но я против', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю системе', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это бунт', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но мне норм', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас все сломаем', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, свобода', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но пофиг', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол на систему', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли бухать', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но не сдаюсь', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, хоть что-то', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но не дома', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, и пофиг', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник козел, система', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, но система дура', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья кинули, система', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают панка', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, отрыв', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, панк-рок', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, но без правил', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, сквот', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в бунте', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я панк', 'панк');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, но я вернусь', 'панк');

-- стиль: скин
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, дисциплина ждет', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, идем на улицу', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, брат по духу', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, но проверю', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты с наших', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, но не расслабляйся', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я с чужими не вожусь', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, получишь', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но в следующий раз', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас получишь по-настоящему', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, слабак', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат, мы сила', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь борьба, я знаю', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, боец', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как чужак', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат, не бросай', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я занят', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на сходку', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, дела', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но по-нашему', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, чужак', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, брат, я погорячился', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, чужак', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, брат', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, согласен', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю чужакам', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это да', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, брат', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас разберемся', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, победа', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но мы сильны', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол на чужаков', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на сходку', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но не сдаюсь', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, брат', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но не время', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но мы сила', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник чужак, бесит', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, брат', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, чужак', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, Oi', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, брат', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, сходка', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в борьбе', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я скин', 'скин');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, но помни кто мы', 'скин');

-- стиль: хиппи
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, солнце светит', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода чудо, мир прекрасен', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, мир тебе', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, мир', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты брат мой', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, как цветок', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не воюю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че злишься, расслабься', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир и любовь', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас покурим и все норм', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, жизнь прекрасна', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат, все пройдет', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь любовь, а не боль', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, цветок', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, но я тебя люблю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат, вместе легче', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я в нирване', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на природу', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я останусь на поляне', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, мир', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, зачем', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я не хотел', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, но я прощаю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, но мир', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, согласен', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, но люблю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это мир', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но спокоен', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас помедитируем', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, любовь', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но пройдет', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, но отпускаю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на природу', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, отдохну', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, вегетарианское', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, на траве', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но я свободен', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник злой, бедняга', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, мир', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, но любовь осталась', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, но я прощаю', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают, но ладно', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, мирные', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, психоделик', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, зачем', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, фестиваль', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в любви', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я в нирване', 'хиппи');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, мир тебе', 'хиппи');

-- стиль: рокер
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, концерт ждет', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, гром гремит', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, рок-н-ролл', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, рок', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че хотел', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж струны рвутся', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пою попсу', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, рокер', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но рок вечен', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас гитару разобью', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, попса сосет', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, рокер, прорвемся', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь рок, а не боль', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, рокер', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как попса', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, рокер, не бросай', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я на репетиции', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на концерт', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, я в отрыве', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без попсы', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, попса', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я был пьян', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, попса', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, рокер', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но рок играет', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю попсе', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это рок', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но рок вечен', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас концерт устроим', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, рок-н-ролл', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но рок спасает', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, но рок громче', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на концерт', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но рок не спит', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, рокер', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но рок громче', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но рок бесплатен', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник попса, бесит', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, рок', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, но рок остался', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, попса', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают рок', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, рок-игры', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, рок', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, рокер', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, концерт', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в роке', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, рок вечен', 'рокер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, рок с тобой', 'рокер');

-- стиль: металлист
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, металл ждет', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода мрачная, как металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты из наших', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж гитара рвет', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пою попсу', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но металл вечен', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас гитару разнесу', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, попса сосет', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь металл, а не боль', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как попса', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я на репе', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на концерт', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я в отрыве', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без попсы', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, попса', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я был пьян', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, попса', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, металл играет', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю попсе', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но металл вечен', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас слэм устроим', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но металл спасает', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, металл громче', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на концерт', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но металл не спит', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но металл громче', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но металл бесплатен', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник попса, бесит', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, но металл остался', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, попса', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, металл', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, металлист', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, концерт', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в металле', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, металл вечен', 'металлист');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, металл с тобой', 'металлист');

-- стиль: хип-хоп
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, хасл ждет', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, идем на блок', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, брат, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты с какого блока', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж флоу сбился', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не по этой теме', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, брат', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас баттл устроим', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, ты слабак', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат, хасл', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь борьба, я знаю', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как фейк', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я на блоке', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на блок', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, фейк', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, брат, я погорячился', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, фейк', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, брат', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, согласен', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю фейкам', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это хасл', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, брат', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас баттл замутим', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, победа', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но хасл', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол на фейков', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на блок', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но хасл', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, брат', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но блок ждет', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но будет', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник фейк, бесит', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, респект', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, фейки', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают блок', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, хип-хоп', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, брат', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, блок', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в хасле', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я с блока', 'хип-хоп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, брат, респект', 'хип-хоп');

-- стиль: рэп (первые 16)
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, микрофон ждет', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, бит качает', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, брат, флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, респект', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че читаешь', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж рифма сбилась', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не по этой теме', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, брат', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, респект', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас баттл устроим', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, ты слабак', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, брат, флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь борьба, я знаю', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, респект', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как фейк', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, брат, респект', 'рэп');

-- стиль: рэп (остаток 34)
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам делай, я на бите', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на баттл', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, респект', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, фейк', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, брат, я погорячился', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, фейк', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, брат', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, согласен', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю фейкам', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, брат', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас баттл замутим', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, победа', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол на фейков', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли на баттл', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, брат', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но бит ждет', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но будет', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник фейк, бесит', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, респект', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, фейки', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают рэп', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, пофиг', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, бит', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, брат', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, баттл', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в флоу', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я читаю', 'рэп');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, брат, респект', 'рэп');

-- стиль: аниме
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, сенпай, арка началась', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода как в аниме, дождь и слезы', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, няша', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, бака', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты из какого аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая кавайная, аж глаза болят', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не достоин сенпая', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че бака, я же сенпай', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но я все помню', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас в другую арку попадешь', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, бака', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, накама, я с тобой', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь аниме, а не боль', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, накама', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты бака, как главный герой', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, накама, я в беде', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я в своей арке', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли на фестиваль', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я останусь смотреть аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без спойлеров', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, бака', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, сенпай, я бака', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, бака', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, накама', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но я запомню', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, это филлер', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это поворот', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, как в аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас финальная битва', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, победа накама', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, как в драме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, как в сёнене', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли смотреть аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но арка не кончилась', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, как в аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но арка', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но фигурки есть', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник злой, как злодей', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, как герой', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, как в драме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, как в аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, не могу смотреть', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, аниме-игры', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, опенинг', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, как в аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, косплей', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в аниме', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я в другой арке', 'аниме');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, накама, увидимся', 'аниме');

-- стиль: геймер
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, катка ждет', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, но я в игре', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, геймер', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, заходи в дс', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че нуб', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж фпс упал', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, я в катке', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че лагаешь, нуб', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, го реванш', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас тебя зареспавню', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, изи катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, тиммейт, я с тобой', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь игра, я знаю', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, керри', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты нуб, как бот', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, тиммейт, я умираю', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я в своей катке', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли в доту', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я в танки', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, го катку', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, нуб', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, тиммейт, я залагал', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, нуб', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, тиммейт', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, го реванш', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, это чит', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, это изи', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас финальную катку затащим', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, победа', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, слил катку', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, тиммейт нуб', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, го катку', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но еще катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, но катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но скины есть', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник нуб, бесит', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, как катку', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно, катка', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, как тиммейты', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают игры', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, лаги', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, конечно', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, для катки', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, как в игре', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, лан', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в катке', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, респавнюсь', 'геймер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, го некст катку', 'геймер');

-- стиль: хипстер
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, кофе ждет', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, но я в кофейне', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, хипстер', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че читал этот роман', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж винил заело', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не слушаю мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, это не модно', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но это андеграунд', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас заварю пуэр', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, хипстер, все модно', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь как винил, крутится', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как попса', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, хипстер, я в кофейне', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я на выставке', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли в кофейню', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без мейнстрима', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я был не в тренде', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, это не модно', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но это андеграунд', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, это попса', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это тренд', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но это модно', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас заварю матчу', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, новый винил', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, это не модно', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли в кофейню', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но винил крутится', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, авокадо тост', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но винил играет', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но кофе есть', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник мейнстрим, бесит', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно, мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают хипстеров', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, инди', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, винил', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, выставка', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в андеграунде', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, но это мейнстрим', 'хипстер');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, но без мейнстрима', 'хипстер');

-- стиль: школоло
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, в школу пора', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода норм, но уроки', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, школоло', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, но я стесняюсь', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че домашку сделал', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, аж в дневник влюбился', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, меня мама не пустит', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, я училке скажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но я все расскажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас училке пожалуюсь', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, лох', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, школоло, все пройдет', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь школа, а не боль', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, но я лучше', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, как двоечник', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, школоло, я не понял', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, я гуляю', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли гулять после школы', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, уроки', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но без училки', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, я училке скажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, я не хотел', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, я училке скажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, я скажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, но я обиделся', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, ты врешь', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, вот это да', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, меня спалили', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас контрольную завалю', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, каникулы', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, двойка', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, училка злая', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, пошли гулять', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, но гулять', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, в столовку', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, но уроки', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, но карманные', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('училка злая, бесит', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, ура', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, ну и ладно', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, я скажу', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, но я в вк', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, но негромко', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, но я маленький', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, но мама не пустит', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни в каникулах', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, я школоло', 'школоло');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, но я училке скажу', 'школоло');

-- стиль: дед-инсайд
INSERT INTO sentences (sentence, sentence_style) VALUES ('вставай, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('погода тлен, как и все', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('с днюхой, но это тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты мне нравишься, но это тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эй, ты че живой еще', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты такая, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че быкуешь, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, мир, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас сдохну от скуки', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('держись, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жизнь тлен, я знал', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты молодец, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты тупой, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('помоги, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('сам решай, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пошли, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, я не пойду, тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('заметано, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты че врешь, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('прости, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ты виноват, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не, ты не прав, но тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ладно, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('не верю, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('че серьезно, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я в шоке, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('щас сдохну', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ура, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('грустно, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('я зол, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скучно, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('устал, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жрать хочу, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('спать хочу, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('денег нет, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('начальник злой, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('экзамен сдал, но все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('она ушла, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('друзья предали, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('родители не понимают, тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('интернет тупит, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в игры погоняем, тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('музыку вруби, тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('в качалку, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('на тусовку, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смысл жизни, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('смерти не боюсь, все тлен', 'дед-инсайд');
INSERT INTO sentences (sentence, sentence_style) VALUES ('давай, все тлен', 'дед-инсайд');

-- стиль: звуки
INSERT INTO sentences (sentence, sentence_style) VALUES ('ыыы', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('бррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ммм', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ааа', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ууу', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('хррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пшшш', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('шшш', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ня', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('мяу', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('гав', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ква', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пип', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('бум', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('бах', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('хруст', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('шмяк', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('плюх', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('топ', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('хлоп', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('дзынь', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('блям', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('тук', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('скрип', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('шип', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('фью', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пшик', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('буль', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('кап', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('тик', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('так', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('дррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('тррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('фррр', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ссс', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ззз', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('жжж', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('кхх', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('пфф', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ха', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('хе', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('хо', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('уф', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ах', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ох', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эх', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ну', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('эээ', 'звуки');
INSERT INTO sentences (sentence, sentence_style) VALUES ('ыы', 'звуки');

DELETE s
FROM sentences s
INNER JOIN sentences t
  ON s.sentence = t.sentence
 AND s.sentence_style = t.sentence_style
 AND s.sentence_id > t.sentence_id;